---
kind: Namespace
apiVersion: v1
metadata:
  name: apache-webapp
---
# Deployment with Bitnami Apache
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache-webapp
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: bitnami/apache:latest
        ports:
        - containerPort: 8080  # Bitnami Apache listens on 8080 by default
        env:
        - name: APACHE_HTTP_PORT_NUMBER
          value: "8080"  # Explicitly set port (optional)
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30  # Give Apache more time to start
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-webapp
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# OpenShift Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apache-route
  namespace: apache-webapp
spec:
  host: apache.apps-crc.testing  # CRC default domain
  to:
    kind: Service
    name: apache-service
  port:
    targetPort: 8080
