apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resource-quota
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 5Gi
    limits.cpu: "2"
    limits.memory: 7Gi
    services: "5"                # Max number of services
    secrets: "4"                # Max secrets
    configmaps: "3"             # Max configmaps