apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: tester-team-quota
spec:
  selector:
    labels:
      matchLabels:
        team: tester
  quota:
    hard:
      requests.cpu: "4"
      requests.memory: "8Gi"
      limits.cpu: "8"
      limits.memory: "16Gi"
      pods: "20"
      persistentvolumeclaims: "10"
      services: "10"
      secrets: "20"
      configmaps: "20"
