---
#Create Project
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: secret-combo-demo
---
#Create secret
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: secret-combo-demo
type: Opaque
data:
  username: bXl1c2VyCg==      # base64 encoded value of 'myuser'
  password: bXlwYXNzd29yZAo=  # base64 encoded value of 'mypassword'
---
#Create Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-combo-demo
  namespace: secret-combo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-combo-demo
  template:
    metadata:
      labels:
        app: secret-combo-demo
    spec:
      containers:
      - name: demo-container
        image: busybox
        command: ["sh", "-c", "echo USERNAME=$USERNAME && echo PASSWORD=$PASSWORD && cat /etc/secrets/username && cat /etc/secrets/password && sleep 600"]
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
...
