#templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
